version: '3.7'
services:
  auto-m4b:
    #image: seanap/auto-m4b
    build: .
    container_name: auto-m4b
    volumes:
      - /Users/johnbachinibarr/docker/auto-m4b/config:/config
      - /Users/johnbachinibarr/docker/auto-m4b/temp:/temp
    environment:
      - PUID=501
      - PGID=20
      - CPU_CORES=2
      - MAKE_BACKUP=N